/*
handles procedures for creating, joining, and ending study sessions
*/

import { z } from "zod";

import { createTRPCRouter, publicProcedure } from "~/server/api/trpc";

export const sessionsRouter = createTRPCRouter({
    create: publicProcedure
    .input(z.object({ 
        mode: z.string(), //could potentially change to z.enum(["mode1", "mode2"])
        status: z.string(), //could potentially change to z.enum(["status1", "status2"])
        planned_duration_minutes: z.number().int().positive(),
        matchedUsers: z.array(z.object({
            userId: z.string().uuid(),
            mathchedWaitTimeSeconds: z.number().int().nonnegative().optional()
        })).min(1)

        /*id (UUID): database handles generating unique IDs
          same with created_at and ended_at should be generated
        */
    }))
    
    .mutation(async ({ ctx, input }) => {
        /*
        TO DO:
        - Call supabase and insert rows into sessions table
        - Save id to be used to creat session participants row
        */

        return await ctx.db.$transaction(async (tx) => { //creates a batch of operations https://www.prisma.io/docs/orm/prisma-client/queries/transactions#the-transaction-api

            const newSession = await tx.session.create({ //table name
                data: {
                    mode: input.mode,
                    status: input.status,
                    planned_duration_minutes: input.planned_duration_minutes
                    // id and created_at needs to be generated by db CODE MISSING
                }
            });

            const userData = await input.matchedUsers.map((user) => {
                return {
                    sessionId: newSession:id, //id generated by db CODE MISSING
                    userId: user.userId,
                    match_wait_time_seconds: user.mathchedWaitTimeSeconds
                }
            })

            await tx.sessionParticipants.createMany({ //table name
                data: userData
            });

        })

        

    }),

    end: publicProcedure
    .input(z.object({ 
        sessionID: z.string().uuid() //aka sessionId either depending on final rable
    }))

    .mutation(async ({ ctx, input }) => {
        /*
        TO DO:
        - Does this happen once both users leave?
        - Update 'sessions' table
            - Change status and ended_at variables for said session
        */
    }),



    leave: publicProcedure
    .input(z.object({ 
        particpantID: z.string().uuid() //the user thats leaving id
    }))
    
    .mutation(async ({ ctx, input }) => {
        /*
        TO DO:
        - set left_at time in session_participants
        - Potentially end the meeting
        */
    })


    /*
    join: publicProcedure
    .input(z.object({ 
        sessionID: z.string() //aka sessionId either depending on final rable
    }))
    
    .mutation(async ({ ctx, input }) => {
        
        TO DO:
        - Verify the user is allowed to join this session or that it is not already full
        - Update session_participants 'user_id' document when user joins
        
    })
    */
    
});