/*
handles procedures for creating, joining, and ending study sessions
*/

import { z } from "zod";

import { createTRPCRouter, publicProcedure, protectedProcedure} from "~/server/api/trpc";

export const sessionsRouter = createTRPCRouter({
    create: protectedProcedure
    .input(z.object({ 

        //NEEDS TO BE CHANGED TO ACTUAL MODES AND STATUSES ONCE FINALIZED
        mode: z.enum(["mode1", "mode2"]),

        //COULD ALSO BE CHANGED
        status: z.enum(["active", "ended"]), //potentially change to z.enum(["status1", "status2"])

        planned_duration_minutes: z.number().int().positive(),
        matchedUsers: z.array(z.object({
            userId: z.string().uuid(),
            matchedWaitTimeSeconds: z.number().int().nonnegative().optional()
        })).min(1)

        /*id (UUID): database handles generating unique IDs
          same with created_at and ended_at should be generated
        */

    }))
    
    .mutation(async ({ ctx, input }) => {

        const {data: newSession, error: sessionError} = await ctx.supabase
        .from('sessions') //table name
        .insert({
                mode: input.mode,
                status: input.status,
                planned_duration_minutes: input.planned_duration_minutes
                // id and created_at needs to be generated by db CODE MISSING
        })

        .select('id') //selecting id to use for session participants table
        .single(); //expecting single row to be inserted

        if(sessionError) {
            console.error("Error creating session:", sessionError);
            throw new Error("Failed to create session");
        }


        const userData = input.matchedUsers.map((user) => ({
            
            session_id: newSession.id, //id generated by db CODE MISSING
            user_id: user.userId,
            match_wait_time_seconds: user.matchedWaitTimeSeconds
            
        }));

        const {error : userError} = await ctx.supabase
        .from('session_participants') //table name
        .insert(userData) //data to insert allows for bulk insert of all matched users with session id
        
        return { sessionId: newSession.id }; //this saves the sessionId to be used for future calls related to this session
        

    }),

    end: protectedProcedure
    .input(z.object({ 
        sessionID: z.string().uuid() //aka sessionId either depending on final rable
    }))

    .mutation(async ({ ctx, input }) => {

        const {error: endError} = await ctx.supabase
        .from('sessions')
        .update({
            status: "ended", //potentially change to z.enum(["status1", "status2"])
            ended_at: new Date().toISOString() //generates current timestamp
        })
        .eq('id', input.sessionID) //find session by id
    }),



    leave: protectedProcedure
    .input(z.object({ 
        sessionID: z.string().uuid() //the session they are leaving
    }))
    
    .mutation(async ({ ctx, input }) => {

        const currentUser = ctx.userObj; //get the current user that is calling this procedure (more security)
        const {error: leaveError} = await ctx.supabase
        .from('session_participants')
        .update({left_at: new Date().toISOString() //generates current timestamp
        })
        .eq('user_id', currentUser.id) //find user by id
        .eq('session_id', input.sessionID) //find session by id
        
        const {data: participants, error: participantsError} = await ctx.supabase
        .from('session_participants')
        .select('*')
        .eq('session_id', input.sessionID) //find session by id

        if (participantsError) {
            console.error("Error updating participant:", participantsError);
            throw new Error("Failed to update participant");
        }

        //check if all participants have left and end session if
        const allLeft = participants.every((participant: any)  => participant.left_at !== null);
        
        if (allLeft) {
            const {error: endError} = await ctx.supabase
            .from('sessions')
            .update({
                status: "ended", //potentially change to z.enum(["status1", "status2"])
                ended_at: new Date().toISOString() //generates current timestamp
            })
            .eq('id', input.sessionID) //find session by id
        }

    }),


    /*
    join: publicProcedure
    .input(z.object({ 
        sessionID: z.string() //aka sessionId either depending on final rable
    }))
    
    .mutation(async ({ ctx, input }) => {
        
        TO DO:
        - Verify the user is allowed to join this session or that it is not already full
        - Update session_participants 'user_id' document when user joins
        
    })
    */
    
});