/*
handles procedures for creating, joining, and ending study sessions
*/

import { z } from "zod";

import { createTRPCRouter, publicProcedure } from "~/server/api/trpc";

export const sessionsRouter = createTRPCRouter({
    create: publicProcedure
    .input(z.object({ 
        mode: z.string(), //could potentially change to z.enum(["mode1", "mode2"])
        status: z.string(), //could potentially change to z.enum(["status1", "status2"])
        planned_duration_minutes: z.number().int().positive(),
        matchedUsers: z.array(z.object({
            userId: z.string().uuid(),
            mathchedWaitTimeSeconds: z.number().int().nonnegative().optional()
        })).min(1)

        /*id (UUID): database handles generating unique IDs
          same with created_at and ended_at should be generated
        */
    }))
    
    .query (async ({ ctx, input }) => {
        /*
        TO DO:
        - Call supabase and insert rows into sessions table
        - Save id to be used to creat session participants row
        */


        const {data: newSession, error: sessionError} = await ctx.supabase
        .from('sessions') //table name
        .insert({
                mode: input.mode,
                status: input.status,
                planned_duration_minutes: input.planned_duration_minutes
                // id and created_at needs to be generated by db CODE MISSING
        })

        .select('id') //selecting id to use for session participants table
        .single(); //expecting single row to be inserted

        if(sessionError) {
            console.error("Error creating session:", sessionError);
            throw new Error("Failed to create session");
        }


        const userData = await input.matchedUsers.map((user) => {
            return {
                sessionId: newSession.id, //id generated by db CODE MISSING
                userId: user.userId,
                match_wait_time_seconds: user.mathchedWaitTimeSeconds
            }
        })

        const {error : userError} = await ctx.supabase
        .from('session_participants') //table name
        .insert(userData) //data to insert allows for bulk insert of all matched users with session id
        

        

    }),

    end: publicProcedure
    .input(z.object({ 
        sessionID: z.string().uuid() //aka sessionId either depending on final rable
    }))

    .mutation(async ({ ctx, input }) => {
        /*
        TO DO:
        - Does this happen once both users leave?
        - Update 'sessions' table
            - Change status and ended_at variables for said session
        */

        const {error: endError} = await ctx.supabase
        .from('sessions')
        .update({
            status: "ended", //potentially change to z.enum(["status1", "status2"])
            ended_at: new Date() //generates current timestamp
        })
        .eq('id', input.sessionID) //find session by id
    }),



    leave: publicProcedure
    .input(z.object({ 
        particpantID: z.string().uuid() //the user thats leaving id
    }))
    
    .mutation(async ({ ctx, input }) => {
        /*
        TO DO:
        - set left_at time in session_participants
        - Potentially end the meeting
        */

        const {error: leaveError} = await ctx.supabase
        .from('session_participants')
        .update({
            left_at: new Date() //generates current timestamp
        })
        .eq('user_id', input.particpantID) //find session by id
    })


    /*
    join: publicProcedure
    .input(z.object({ 
        sessionID: z.string() //aka sessionId either depending on final rable
    }))
    
    .mutation(async ({ ctx, input }) => {
        
        TO DO:
        - Verify the user is allowed to join this session or that it is not already full
        - Update session_participants 'user_id' document when user joins
        
    })
    */
    
});